language: python
python:
  - 3.3
install:
  - lsb_release -a
  - sudo sh -ec 'apt-get update; apt-get install devscripts'
  - git clone https://github.com/g2p/python-debian.git
  - (cd python-debian; debian/rules setup.py)
  - pip install ./python-debian .
script:
  - time ./run-tests

