#!/usr/bin/python3.3

import argparse
import glob
import os
import shlex
import shutil
import subprocess
import sys
import tempfile

import gitdeb

KEYRINGS_DIR = os.path.expanduser('~/.local/share/public-keyrings')

def cmd_get_keyrings(args):
    os.makedirs(KEYRINGS_DIR, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix='git-deb-', suffix='.keyrings') as tdir:
        subprocess.check_call(
            'apt-get source -b debian-keyring'.split(), cwd=tdir)
        krs = glob.glob(tdir + '/debian-keyring-*/output/keyrings/*.gpg') \
            + glob.glob(tdir + '/debian-keyring-*/output/keyrings/*.pgp')
        if not krs:
            print('No keyrings found, incompatible change in debian-keyring?',
                  file=sys.stderr)
            return 2
        for krn in krs:
            shutil.copy(krn, KEYRINGS_DIR)


def cmd_export(args):
    assert args.refname[0] != '-'
    import debian.deb822
    h0 = subprocess.check_output(
        ['git', 'show-ref', '-s', '--', args.refname]).rstrip().decode()
    control_file = debian.deb822.Deb822(
        subprocess.check_output(
            ['git', 'show', h0 + ':debian/control']))
    pkgname = control_file['Source']
    with subprocess.Popen(
        ['git', 'show', h0 + ':debian/changelog'],
        universal_newlines=True, stdout=subprocess.PIPE
    ) as proc:
        author, date, version = gitdeb.parse_changelog(proc.stdout, [], just_one=True)
        proc.kill()
    if '-' in version:
        native = False
        orig_version, debian_revision = version.split('-')
        with subprocess.Popen(
            ['git', 'log', '--format=%P', h0],
            universal_newlines=True, stdout=subprocess.PIPE
        ) as proc:
            for line in proc.stdout:
                parents = line.split()
                assert len(parents) < 3
                if len(parents) == 2:
                    p0, p1 = parents
                    break
                if len(parents) == 0:
                    p1, = prev_parents
                    break
                prev_parents = parents
        co_name = '{}-{}'.format(pkgname, orig_version)
    else:
        native = True
        out = subprocess.check_output(
            ['git', 'log', '-n1', '--format=%P', h0]).decode()
        parents = out.split()
        # Will fail with atop_1.23 (non-native without a debian rev)
        # Using the version number works fine with policy-compliant packages,
        # and it's hard to make a heuristic for the rest.
        assert len(parents) < 2, parents
        co_name = '{}-{}'.format(pkgname, version)
    with tempfile.TemporaryDirectory(prefix='git-deb-', suffix='.export') as tdir:
        tdir += '/'
        co_dir = tdir + co_name
        os.mkdir(co_dir)
        subprocess.check_call(
            'git archive {} |{{ cd {}; tar x; }}'
            .format(shlex.quote(h0), shlex.quote(co_dir)), shell=True)
        if not native:
            with open(tdir + '{}_{}.orig.tar'.format(pkgname, orig_version), 'wb') as af:
                subprocess.check_call([
                    'git', 'archive', '--prefix',
                    '{}-{}/'.format(pkgname, orig_version), p1], stdout=af)
            subprocess.check_call(['gzip', '--', af.name])
        subprocess.check_call(['dpkg-source', '-b', co_name], cwd=tdir)
        shutil.rmtree(co_dir)
        for name in os.listdir(tdir):
            shutil.copy(tdir + name, name)


parser = argparse.ArgumentParser()
commands = parser.add_subparsers(dest='command')
sp_get_keyrings = commands.add_parser('get-keyrings')
sp_get_keyrings.set_defaults(action=cmd_get_keyrings)
sp_export = commands.add_parser('export')
sp_export.set_defaults(action=cmd_export)
sp_export.add_argument('refname', nargs='?', default='HEAD')
args = parser.parse_args()
if sys.argv[1:]:
    sys.exit(args.action(args))
else:
    parser.print_help()

